Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of
shape [3 ∗ 3] and perform the following task:
Task to be performed:
Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄)

In [7]:
import numpy as np
P =[]
Q =[]

P= [int(i) for i in input().split()]
Q= [int(i) for i in input().split()]

P= np.array(P).reshape(3,3)
Q= np.array(Q).reshape(3,3)

R = P -Q
print(R)

23 56 87 3 6 96 4 6 78
12 34 54 7 2 54 6 2 78
[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
